// Note: This file has been modified from its original version by the RecorderX derivative project.
// The original repository was developed by Chinmai H B (snap24) under the Apache License 2.0.
plugins {
    id "com.android.application"
}

android {
    namespace "com.codeshowoff.recorder"
    compileSdk 34

    defaultConfig {
        applicationId "com.codeshowoff.recorder"
        minSdk 29
        targetSdk 34
        versionCode 8
        versionName "3.1.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            storeFile file("release.jks")
            storePassword "password"
            keyAlias "key0"
            keyPassword "password"
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    dependenciesInfo {
        includeInBundle = false
        includeInApk = false
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:1.6.1"
    implementation "com.google.android.material:material:1.11.0"
    implementation "androidx.constraintlayout:constraintlayout:2.1.4"
}
